spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/runway
    username: runway
    password: runway@123
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  flyway:
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
