spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/runway
    username: runway
    password: runway@123
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true:
  cache:
    type: infinispan
    infinispan:
      config: classpath:cache/infinispan.xml
  flyway:
    schemas: runway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'